extends:
  - stylelint-config-standard
  - stylelint-config-recommended-vue
ignoreFiles:
  - '**/*.html'
  - 'node_modules/**'
rules:
  selector-pseudo-element-colon-notation: 'single'
  block-no-empty: null
  declaration-empty-line-before: null
  color-function-notation: null
  alpha-value-notation: null
  no-descending-specificity: null
  declaration-block-no-redundant-longhand-properties: null
  shorthand-property-no-redundant-values: null
  color-hex-length: null
  comment-empty-line-before: null
  comment-whitespace-inside: null
  custom-property-empty-line-before: null
  no-empty-source: null
  font-family-name-quotes: always-where-recommended
  max-nesting-depth:
    - 4
    - ignoreAtRules:
        - each
        - media
        - supports
        - include
  selector-class-pattern:
    - '(^[a-z0-9_-]+$|^[a-zA-Z0-9]+$|^[a-zA-Z0-9_-]+$)'
    - message: Selector should be written in lowercase with hyphens (selector-class-pattern)
  selector-max-compound-selectors: 4
  selector-max-id: 1
  selector-no-qualifying-type:
    - true
    - ignore:
        - attribute
        - class
